baseURL = "/"
title = "yshalsager"
copyright = "Copyright © 2013-{year} yshalsager. All Rights Reserved."
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
timeout = "180s"
title_sections = false
ignoreLogs = ["err-youtube-remote"]

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "Offline", "RSS", "SearchIndex", "WebAppManifest"]

[taxonomies]
authors = "authors"
categories = "categories"
series = "series"
tags = "tags"

[build]
writeStats = true

[related]
includeNewer = true
threshold = 10
toLower = false

[[related.indices]]
name = "keywords"
weight = 100

[[related.indices]]
name = "tags"
weight = 80

[[related.indices]]
name = "categories"
weight = 60

[[related.indices]]
name = "series"
weight = 60

[[related.indices]]
name = "authors"
weight = 10

[[related.indices]]
name = "date"
weight = 10

[security.funcs]
getenv = ["^HUGO", "CI$", "PWD"]
