baseURL = "/"
copyright = "Copyright © 2013-{year} yshalsager. All Rights Reserved."
theme = "hugo-theme-bootstrap"
title = "yshalsager"

# Multilingual mode
defaultContentLanguage = "en" 
defaultContentLanguageInSubdir = true # If you use only one language comment this option
#disableLanguages = ["fr", "zh-cn" ,"zh-tw"] # For disable one or more language

# Pagination
paginate = 10
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

timeout = "120s"

[blackfriday]
hrefTargetBlank = true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["json"]

[outputFormats]
[outputFormats.RSS]
baseName = "rss"
mediatype = "application/rss"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

enableGitInfo = true

[build]
ignoreLogs = ["err-youtube-remote"]
writeStats = true
