[[main]]
  name = "下拉菜单"
  identifier = "dropdown"
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  parent = "dropdown"
  id = "github"
  name = "Github"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  pre = '<i class="fab fa-fw fa-github"></i>'
