[[main]]
  name = "مشاريعي"
  identifier = "projects"
  pre = '<i class="fas fa-fw fa-code"></i>'
  url = "ar/projects"
  weight = 80
[[main]]
  name = "حديقتي الرقمية"
  identifier = "digital-garden"
  pre = '<i class="fas fa-fw fa-leaf"></i>'
  url = "ar/notes"
  weight = 90
