[[main]]
  name = "مشاريعي"
  identifier = "projects"
  pageRef = "/projects"
  weight = 80
  [main.params.icon]
    vendor = "fas"
    name = "code"
[[main]]
  name = "حديقتي الرقمية"
  identifier = "digital-garden"
  url = "https://notes.yshalsager.com/ar/"
  weight = 90
  [main.params.icon]
    vendor = "fas"
    name = "leaf"
[[main]]
  name = "الأرشيف"
  identifier = "archives"
  pageRef = "/archives"
  weight = 100
  [main.params.icon]
    vendor = "fas"
    name = "box-archive"
[[main]]
  name = "الأقسام"
  identifier = "categories"
  pageRef = "/categories"
  weight = 110
  [main.params.icon]
    vendor = "fas"
    name = "folder"
[[main]]
  name = "السلاسل"
  identifier = "series"
  pageRef = "/series"
  weight = 120
  [main.params.icon]
    vendor = "fas"
    name = "layer-group"
[[main]]
  name = "التسميات"
  identifier = "tags"
  pageRef = "/tags"
  weight = 130
  [main.params.icon]
    vendor = "fas"
    name = "tags"
