mainSections = ["posts"]
repo = "https://github.com/yshalsager/personal_website"
# mainSections = ["post", "posts"] # Default to ["posts"].

# titleSeparator = "|" # Title separator. Default to "-".
description = "yshalsager's personal website and blog."
keywords = "yshalsager, Youssif Shaaban, Youssif Shaaban Alsager"
# images = ["site-feature-image.jpg"]
rssDescription = "Latest posts from "

logo = "images/logo.png" # Logo image. Default to "images/logo.webp".
# logo = false # Disable Logo
brand = ""

palette = "blue" # Default palette. Optional.
# palettes = ["blue", "blue gray", "brown"] # Available palettes. Default to ALL.
# palettes = [] # Disable palette switcher.

# color = "dark" # light, dark or dynamic. Default to dynamic.

# fullWidth = true # Full width.
# fixedHeader = false # Turn on/off fixed header.

dateFormat = "2 Jan, 2006"

# Google Adsense
googleAdsense = ""

# math = true # Enable math globally.
# toc = false # Disable TOC globally.
breadcrumb = true # Disable breadcrumb
# diagram = true
# socialshare = false # disable social network sharing
# searchBar = false # disable search-bar

poweredBy = false # Whether to show powered by.

# readingTime = false # Whether to display the reading time.
# postDate = false # Whether to display the post date in the post meta section.

# featuredPostCount = 10 # The number of featured posts shown in sidebar. Turn off by setting it to false.
# recentPostCount = 10 # The number of recent posts shown in sidebar. Turn off by setting it to false.
# relatedPostCount = 10 # The number of related posts. Turn off by setting it to false.
# categoryCount = 10 # The number of categories shown in sidebar. Turn off by setting it to false.
# tagCount = 10 # The number of tags shown in sidebar. Turn off by setting it to false.
# seriesCount = 10 # The number of series shown in sidebar. Turn off by setting it to false.
taxonomyPaginate = 10 # Default to 10.
taxonomyPostCount = 20 # The number of posts of taxonomy. Turn off by setting it to false.
countTaxonomyPosts = false # Count posts of taxonomy.

sidebarTaxonomies = ["categories", "tags", "series"] # The order of taxonomies on the sidebar.

# pinnedPost = false # Turn on/off pinned posts.
pinnedPostCount = 3 # The number of pinned posts.

# Custom CSS and JS
customCSS = [
]
customJS = [
]

tocWordCount = 120 # TOC is displayed only if the post's word count exceeds this value.

titleCase = true # Capitalized title.

viewer = true # Image Viewer

[codeBlock]
  # maxLines = 8
  lineNos = true # true/false represents that show/hide the line numbers by default.

[post]
  excerpt = "description"
  excerptMaxLength = 300

[archive]
  #paginate = 8 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

[analytics]
  # baidu = "" # Baidu Analytics

# Site verification
[siteVerification]
  google = ""
  bing = ""
  baidu = ""
  baiduUnion = "" # Baidu Union
  so = ""
  sogou = ""
  shenma = ""

[creativeCommons]
  by = true # Credit must be given to you, the creator.
  # nc = true # Only noncommercial use of your work is permitted.
  # nd = true # No derivatives or adaptations of your work are permitted.
  # sa = true # Adaptations must be shared under the same terms.

#[utterances]
  #repo = "razonyang/hugo-theme-bootstrap-comments" # Replace with your repository.
  #issueTerm = "pathname" # pathname, url, title, og:title
  #label = "comment"
  # By default, light and dark mode correspond to github-light and github-dark, respectively.
  # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
  #theme = "" 

[search]
  paginate = 10 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    isCaseSensitive = false
    minMatchCharLength = 3
    threshold = 0.1
    # distance = 100
    useExtendedSearch = true

[reward]
  paypal = "images/reward/paypal.png"
  liberapay = "images/reward/liberapay.png"

#[share]
  #addThis = "" # AddThis pubid.

[fontSize] # Comment or remove this settings to disable font size switcher.
  # extraSmall = ".8rem"
  # small = ".9rem"
  # large = "1.1rem"
  # extraLarge = "1.2rem"

[pwa]
  [pwa.manifest]
    # name = "" # Default to site title.
    short_name = "yshalsager"
    # display = "fullscreen" # Default to standalone.
    # description = "" # Default to site description.
    theme_color = "#1565c0"
    background_color = "#f6f8fa"

    # Icons
    [[pwa.manifest.icons]]
      sizes = "96x96"
      src = "/images/favicons/favicon-96x96.png"
    [[pwa.manifest.icons]]
      sizes = "144x144"
      src = "/images/favicons/android-icon-144x144.png"
    [[pwa.manifest.icons]]
      sizes = "512x512"
      src = "/images/favicons/android-chrome-512x512.png"
