description = "yshalsager's personal website and blog."

[hb]
full_width = false
logo = "favicon.png"
sass_transpiler = "libsass"

[hb.header]
brand = ""

[hb.header.socials]
email = "contact@yshalsager.com"
github = "yshalsager"
rss = true

[hb.footer.socials]
email = "contact@yshalsager.com"
github = "yshalsager"
gitlab = "yshalsager"
liberapay = "yshalsager"
linkedin = "yshalsager"
paypal = "yshalsager"
telegram = "yshalsager"
twitter = "yshalsager"
youtube = "UCr6WUYZ1ErKbXwnCL_oxSCw"
rss = true

[hb.blog]
paginate = 10
list_cols_md = 2
list_cols_lg = 3
post_thumbnail = true
post_thumbnail_placeholder = "yshalsager"

[hb.blog.home]
featured_posts = 5
pinned_posts_position = "list"
main_sections = ["posts"]

[hb.blog.toc]
position = "content"

[hb.blog.sidebar]
position = "start"
width = 0.35
sticky = true

[hb.blog.sidebar.profile]
avatar = "/images/profile.png"
title = "Youssif Shaaban Alsager"
description = "Software Developer and Technical Writer / Translator."
location = "Egypt"
avatar_size = 100

[hb.blog.sidebar.profile.socials]
email = "contact@yshalsager.com"
github = "yshalsager"
linkedin = "yshalsager"
telegram = "yshalsager"
twitter = "yshalsager"
youtube = "UCr6WUYZ1ErKbXwnCL_oxSCw"
rss = true

[hb.blog.sidebar.posts]
recent_count = 10
featured_count = 10

[hb.blog.sidebar.taxonomies]
count = false
limit = 20
style = "pills"
separate = false

[hb.blog.giscus]
repo = "yshalsager/personal_website"
repo_id = "R_kgDOGTRR0g"
category_id = "DIC_kwDOGTRR0s4B_pe_"

[hb.content_panel.repo]
service = "github"
repo = "yshalsager/personal_website"
branch = "master"

[hb.google_fonts]
[[hb.google_fonts.families]]
name = "Noto Naskh Arabic"
[[hb.google_fonts.families]]
name = "Noto Sans"

[search]
stall_threshold = 300
min_match_char_length = 2
case_sensitive = false

[pwa]
icon_path = "favicon.png"

[pwa.manifest]
short_name = "yshalsager"
background_color = "#f6f8fa"
theme_color = "#1565c0"

[hugopress.modules.hb-custom.hooks.hb-blog-post-content-end]

[hugopress.modules.hb-blog-sidebar-taxonomies.hooks.hb-blog-sidebar]
weight = 3

[hugopress.modules.hb-blog-sidebar-posts.hooks.hb-blog-sidebar]
weight = 2
