email = "contact@yshalsager.com"
#facebook = "yourfacebookusername"
github = "yshalsager"
gitlab = "yshalsager"
linkedin = "yshalsager"
#stackoverflow = "yourstackoverflowuserid"
twitter = "yshalsager"
#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#instagram = "yourinstagramusername"
#quora = "yshalsager"
#tumblr = "yourtumblrusername"
#reddit = "yourredditusername"
telegram = "yshalsager"
#qq = "yourqqnumber"
#dockerhub = "yshalsager"
#bitbucket = "yourbitbucketworkspaceid"
#kaggle = "yourkaggleusername"
#medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm = "yourlastfmusername"
#bilibili = "yourbilibiliuserid"
youtube = "UCr6WUYZ1ErKbXwnCL_oxSCw"
#discord = "yourdiscordinvitecode"
#discourse = "https://yourforum.tld"
#facebookgroup = "yourfacebookgroupname"
#tiktok = "yourtiktokusername"
#pinterest = "yourpinterestusername"
