email = "contact@yshalsager.com"
github = "yshalsager"
gitlab = "yshalsager"
linkedin = "yshalsager"
twitter = "yshalsager"
telegram = "yshalsager"
youtube = "UCr6WUYZ1ErKbXwnCL_oxSCw"
liberapay = "yshalsager"
paypal="yshalsager"
#patreon="XiaomiFirmwareUpdater"
